### ISSUE TITLE
Dúvida sobre o projeto Front-End

### ISSUE THREAD

**Issue by icarobteles** [chuva-inc/exercicios-2023#1]
Olá, gostaria de esclarecer uma dúvida sobre o projeto de HTML + CSS + TypeScript!

Existe algum protótipo que deve ser seguido em relação ao design? Ou apenas seguir as instruções dos elementos que devem conter e com quais valores e atributos? Verifiquei todo o código e surgiu essa dúvida.

**Comment by marianafurriel** [comment]
Também gostaria de saber!

**Comment by ChristianSouza12** [comment]
Estou com a mesma duvida!

**Comment by Lucas-dev-br** [comment]
Estou com essa mesma duvida.

**Comment by deivison556** [comment]
Eu estou com a mesma dúvida em relação ao exercício. Sinceramente, eu tenho a impressão que está vago, o que precisa ser feito no Typescript+ HTML+ CSS. Poderia explicar de forma mais clara, o que deve ser feito? Obrigado pela atenção 🙂

**Comment by icarobteles** [comment]
Pessoal, parece que atualizaram o repositório com o protótipo de alta fidelidade, agora é só seguir! Boa sorte a todos.

**Comment by icarobteles** [comment]
Vou aguardar alguma resposta deles, caso queiram acrescentar alguma informação diretamente por aqui, após isso a issue pode ser fechada.

**Comment by wundo** [comment]
Oi @icarobteles @deivison556 @Lucas-dev-br @ChristianSouza12 @marianafurriel 
O link pro Figma estava no formulário que te mandamos no email, mas ontem adicionamos aqui também no repo -> https://github.com/chuva-inc/exercicios-2023/commit/3aa0de7c92821e89b7f861ed2737b38d78138ccf

PS: Vocês viram os vídeos lá no Telegram?
