### ISSUE TITLE
Resolução

### ISSUE THREAD

**Issue by patiAmaral** [chuva-inc/exercicios-2023#19]
Boa tarde.
Em relação ao exercício Typescript + HTML + SCSS
Eu nao consegui entender se é para ser feita uma nova pagina de trabalho a partir do protótipo que voces disbonibilizaram, ou se é para corrrigir os erros existentes no codigo de voces. 
Ou ainda, se é para fazer ambas as coisas, criar uma nova pagina de trabalho sem os erros que existem no protótipo do exercício. 

Se possível, gostaria de um passo a passo mais detalhado sobre o que e como deve ser feito. 
Obrigada.

**Comment by wundo** [comment]
Oi @patiAmaral é pra implementar as telas que passamos usando o app de angular fornecido como base :)

PS: Entra no telegram, lá tem um vídeo detalhado explicando isso
