### ISSUE TITLE
Dúvido sobre o projeto front-end HTML, CSS e TypeScript

### ISSUE THREAD

**Issue by SantosFab** [chuva-inc/exercicios-2023#2]
Olá, Bom dia, estou com uma dúvida para entender o objetivo do projeto. Nunca usei o Angular e Cypress, contudo seguindo o passo a passo das orientações do projeto. Pelo o que entendi do relatório do Cypress, tá tudo certo. Sendo assim, o objetivo do projeto é fazer um novo layout contendo as especificações do teste Cypress?

**Comment by the-pedropaulo** [comment]
Tenho a mesma dúvida

**Comment by wundo** [comment]
Oi @SantosFab,
Se você olhar aqui nesse commit https://github.com/chuva-inc/exercicios-2023/commit/3aa0de7c92821e89b7f861ed2737b38d78138ccf

Adicionamos ontem mais detalhes sobre o protótipo :)

Ficou claro?
