### ISSUE TITLE
Dúvida sobre o Desafio de Dart

### ISSUE THREAD

**Issue by Brennez** [chuva-inc/exercicios-2023#3]
Percebi que o diretório destinado ao desafio de Dart está vazio. Dessa forma, fiquei na dúvida se não deve ter um desafio proposto para a linguagem Dart ou se foi um erro ao subir os arquivos pro repositório remoto.

**Comment by SantosFab** [comment]
Também fiquei confuso, porque há um commit só para - pelo comentário dele: "garante que pasta pro dart/flutter existe"

**Comment by the-pedropaulo** [comment]
Provavelmente o desafio está sendo preparado ainda. Então os únicos disponíveis são: php e ts

**Comment by wundo** [comment]
Exatamente o que o @the-pedropaulo falou, eu inclusive fiz um vídeo sobre isso lá no Telegram, não sei se vocês viram.
