### ISSUE TITLE
Error: Could not find the '@angular-devkit/build-angular:dev-server' builder's node package.

### ISSUE THREAD

**Issue by TiagoNarita** [chuva-inc/exercicios-2023#39]
Tem alguma coisa de errada quando eu vou instalar minhas dependencias. após executar o comando ng serve ele da esse erro. tentei novamente esses comandos: 

rm -rf node_modules
npm install

reinstalei o angular mas mesmo assim continuo nisso.

grato.

**Comment by alex-yudi** [comment]
Verifique se rodando o "npm run ng serve" funciona pra vc, lembre tbm de estar na página do projeto.
