### ISSUE TITLE
Dúvida em relação a interface

### ISSUE THREAD

**Issue by LetzC** [chuva-inc/exercicios-2023#4]
Boa tarde! Rodei os testes e verifiquei os requisitos que o projeto deve possuir. Sobre o protótipo, podemos fazer alterações ou deve ser seguido fielmente?

**Comment by wundo** [comment]
Oi @LetzC o protótipo do Figma?

**Comment by LetzC** [comment]
> Oi @LetzC o protótipo do Figma?

Boa tarde, isso o Figma. Se posso por efeito de hover por exemplo.

**Comment by wundo** [comment]
oi @LetzC pode por sim :)

**Comment by LetzC** [comment]
> oi @LetzC pode por sim :)

Muito obrigada :)
