### ISSUE TITLE
Problema com testes de integração Flutter - Android

### ISSUE THREAD

**Issue by lealvesrs** [chuva-inc/exercicios-2023#41]
Olá! Logo após fazer um fork do repositório (ainda sem alterar o código da parte de Dart, mantendo exatamente como estava no repo da Chuva) tentei executar os testes de integração.
No entanto, recebia o erro abaixo:
![error](https://github.com/chuva-inc/exercicios-2024/assets/54076753/2f24a044-ef06-4825-8616-a4d75cf875d4)

Tentei executar várias vezes, alterei a permissão das pastas, rodei em linux, windows e inclusive troquei o dispositivo físico Android que eu estava depurando. Mesmo assim o erro persistiu.
No telegram, encontrei algumas mensagens de uma gotícula que teve o mesmo problema e ele comentava que **o erro poderia estar relacionado com o uso do Android**.

Para testar se o problema era, de fato, os testes no Android, consegui emprestado um Macbook e realizei novamente os testes, **obtendo sucesso (surpreendentemente!!)**, como pode ser visto abaixo:
![WhatsApp Image 2024-04-02 at 7 12 44 PM](https://github.com/chuva-inc/exercicios-2024/assets/54076753/8e9ffe13-6709-4650-9bc8-a043c830ca42)

Além disso, mesmo quando saio do local e subo para o Github também tenho problemas, já que **a verificação dos testes para de ser executada após 12 minutos e recebo erro de time out.** . Isso me preocupa, pois foi dito que _"Só serão considerados para correção testes em que as verificações do Github Actions estejam passando (verdinhas)."_ 

Erro das Actions:
![errorTimeOut](https://github.com/chuva-inc/exercicios-2024/assets/54076753/4bdb80d1-b33a-42ab-aaff-2794a7b582fc)

Com isso, **gostaria de saber se posso continuar desenvolvendo o aplicativo, mesmo que os testes de integração só estejam rodando em IOS e que as verificações do Github Action não estejam passando**. 

-> IMPORTANTE: Todos esses testes foram executados no fork original, sem que eu tivesse feito alguma alteração e também após alterações.

**Comment by wundo** [comment]
Oi Letícia, obrigado por reportar a Issue, vou dar uma olhada. Que versão do flutter você está no seu local?
