### ISSUE TITLE
Gostaria de saber se rodei os testes certo

### ISSUE THREAD

**Issue by joaoadsistemas** [chuva-inc/exercicios-2023#52]
Recebi uma mensagem falando que não rodei meus testes no github, porém não achei nada sobre como fazer isso na documentação. Apenas realizei os testes que foram mandados (npm run test, npx cypress open --env type=base). Os testes todos passaram e as prints estão na devida pasta do cypress. Gostaria de saber se está tudo certo, e se não estiver, o que posso fazer.

**Comment by wundo** [comment]
@joaoadsistemas explicamos como fazer isso no telegram :)
