### ISSUE TITLE
Duvida em relacao ao Actions

### ISSUE THREAD

**Issue by marcosandradetf** [chuva-inc/exercicios-2023#6]
Boa noite!
Eu fiz o fork, fiz os commits e por fim o push, verifiquei os arquivos .yml. Mas o actions simplesmente nao acusa nada. O que pode estar acontecendo ?

**Comment by wundo** [comment]
Acabei de checar no seu repo, e pelo que eu vi você se encontrou né?

<img width="734" alt="Screenshot 2023-10-09 at 23 11 00" src="https://github.com/chuva-inc/exercicios-2023/assets/113942/c74073e3-86f2-47b8-bdb5-bb4dfb8fa0cf">

Marcando como fechado

**Comment by marcosandradetf** [comment]
Sim, consegui rsrs
