### ISSUE TITLE
Dúvida relacionada ao último teste no projeto de frontend

### ISSUE THREAD

**Issue by samirpegado** [chuva-inc/exercicios-2023#7]
Olá, boa tarde! Tudo bem com vocês? 

Tenho uma dúvida relacionada ao último teste no projeto de frontend.

No seguinte trecho de código:
it('enviar o formulário exibe mensagem de sucesso', () => {
  cy.get('.btn-create-topic').click();
  cy.get('button').click();
  cy.get('body').contains('Aguardando feedback dos autores');
  cy.compareSnapshot('Trabalho - Tópico enviado');
});

A minha dúvida é a seguinte: No teste, não seria mais apropriado especificar a classe do botão que está sendo clicado durante o envio do formulário? Parece que o teste está tentando clicar em todos os botões da página.

Obrigado.

**Comment by darciojunior** [comment]
Meu teste está travando no mesmo local. Tentei reduzir o número de botões trocando por divs, mas alguns botões são necessários. Espero que eles deem alguma resposta aqui.

**Comment by samirpegado** [comment]
Eles responderam no Telegram. 
Disseram que eu poderia mudar o código e por a classe do meu botão de envio do formulário no código do Cypress.
Eu fiz a alteração e passou em todos os testes.

(resposta editada por conter resolução)

**Comment by wundo** [comment]
Como falamos no Telegram, você pode atualizar o cypress.
